//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRequestAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerRequestAccount()
        {
            this.CustomerCredentials = new HashSet<CustomerCredential>();
        }
    
        public int CustomerId { get; set; }
        public string AccountType { get; set; }
        public string BankState { get; set; }
        public string BankCity { get; set; }
        public string BankBranch { get; set; }
        public string BranchIFSC { get; set; }
        public string CustomerName { get; set; }
        public string CustomerGender { get; set; }
        public Nullable<System.DateTime> CustomerDOB { get; set; }
        public Nullable<int> CustomerMobileNumber { get; set; }
        public string CustomerBalance { get; set; }
        public int CustomerAadharCardNumber { get; set; }
        public string CustomerEmailId { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerState { get; set; }
        public string CustomerCity { get; set; }
        public Nullable<int> CustomerPIN { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCredential> CustomerCredentials { get; set; }
    }
}
