//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCredential
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerCredential()
        {
            this.TransactionTables = new HashSet<TransactionTable>();
        }
    
        public string AccountNumber { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public string Password { get; set; }
        public int IsApporved { get; set; }
        public int Status { get; set; }
        public int TotalCnt { get; set; }
    
        public virtual CustomerRequestAccount CustomerRequestAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionTable> TransactionTables { get; set; }
    }
}
